-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  bookmark_title text not null,
  bookmark_url text not null,
  bookmark_description text,
  bookmark_rating NUMERIC not null
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (bookmark_title, bookmark_url, bookmark_description, bookmark_rating)
values
  ('Thinkful', 'https://www.thinkful.com', 'Think outside the classroom', 5),
  ('Google', 'https://www.google.com', 'Where we find everything else', 4),
  ('Youtube', 'https://youtube.com', 'Watch videos and more', 5),
  ('Citibank', 'https://citibank.com', 'Turn everyday purchases into something bigger', 5),
  ('Reddit', 'https://reddit.com', 'Connect, communicate, and share', 3),
  ('Aspiration', 'https://aspiration.com', 'Built for you, built for the planet', 5),
  ('Amazon', 'https://amazon.com', 'Shop now and find the best deals', 2),
  ('Facebook', 'https://facebook.com', 'One day we will rule the world', 5),
  ('Airbnb', 'https://airbnb.com', 'Book unique places to stay and things to do.', 5),
  ('Treehouse', 'https://treehouse.com', 'Learn to code, gain a new skill, get a new job', 5);